services:
  redis:
    image: redis:8.4-alpine
    container_name: sample-stand-redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - sample-stand-redis-data:/data

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: sample-stand-redisinsight
    restart: unless-stopped
    ports:
      - "8001:5540"
    depends_on:
      - redis
    volumes:
      - sample-stand-redisinsight-db:/db
    environment:
      - RI_STDOUT_LOGGER=true

volumes:
  sample-stand-redis-data:
  sample-stand-redisinsight-db:
